version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: kozteg/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  frontend:
    env_file: .env
    iamge: kozteg/taski_frontend
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/
  gateway:
    image: kozteg/taski_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
